### ISSUE TITLE
URL短縮サービスの開発

### ISSUE THREAD

**Issue by Yasshi-cookie** [Yasshi-cookie/link-minimizer#1]
# ※モチベが下がる前にミニマムの実装でデプロイまでやってしまおう

# TODO
- [x] 仕様を定義する
- [x] 実装
- [ ] デプロイ・CI/CDの設定
- [ ] デプロイ後の改善対応

### 要求定義
- 絶対必要なもの
  - 長いURLを入れたら、短いURLを返す機能が欲しい
  - その短いURLをクリックしたら元のリンク先にとべる
- 不要なもの
  - 編集・削除機能

### メモ
- 短縮したURLに使える文字は？
  - 0〜9の数値とa〜z、A〜Zの文字の組み合わせ
- 1日あたり1億件のURLが生成され、このシステムは10年間稼働すると仮定する

### 要件定義
- 機能要件
  - URL短縮ページ
  - 生成したURLの一覧ページ
- 非機能要件
  - 1日1億件 = 1秒間に1100件ほどのトラフィックを捌ける必要がある
  - 10年間稼働している中で生成した短いURLが重複することがないようにする

### 設計
- API
  - URL短縮API（与えられたURLに対して、そのURLと短いURLの組みを永続化し、短いURLを返す）
    - POST api/minimize
    - パラメーター
      - long_url：短くしたい長いURL
    - レスポンス
      - short_url：短くしたURL
  - リダイレクトAPI（短いURLが与えられると、元のURLに301リダイレクトさせる）
    - GET api/go/{short_url}
    - パラメーター
      - short_url：短くされたURL
    - レスポンス
      - ステータスコード：301（あるいは302）
      - ヘッダー
        - location：元のURL
- UI
  - URL短縮ページ（ユーザーから任意のURLを受け取り、短縮したURLを返す）

## 実装
- [x] バックエンド
  - [x] URL短縮API：https://github.com/Yasshi-cookie/link-minimizer/pull/2
  - [x] リダイレクトAPI：https://github.com/Yasshi-cookie/link-minimizer/pull/3
- [x] フロントエンド
  - [x] URL短縮ページ：https://github.com/Yasshi-cookie/link-minimizer-front/pull/4

## デプロイ・CI/CDの設定
- [ ] AWS側で必要なサービス・リソースを作成
  - [ ] ECS
  - [ ] ECR
  - [ ] LoadBalancer
  - [ ] RDS
- [ ] CI/CD（Github Actions）

### バグの修正
- [ ] このサービスで生成されたURLを入力できてしまう。生成される短縮URLをクリックするとリダイレクトが無限に繰り返させる可能性がある。

### 改善対応
- [ ] バックエンド
  - [ ] ソフトウェアテスト
    - [ ] Uniiテスト
    - [ ] Featureテスト
  - [ ] エラーハンドリングの体系化（Handlerクラス、Controller側の404、500エラーレスポンスの定義）
- [ ] フロントエンド
  - [ ] E2Eテスト
- [ ] インフラ
  - [ ] CloudFrontでバックエンド側の「/api/go/...」のパスをキャッシュさせる
